# Site settings
author: Thomas Brown
title: My Journey as a Data Science Student
header-img: img/home-bg.png
email: thomaskbrown18@gmail.com
copyright_name: Thomas Brown
description: > # this means to ignore newlines until "baseurl:"
  Flatiron School's Data Science Course
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  thomaskbrown18

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
